### ISSUE TITLE
Subsections?

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022#2]
Maybe it would make sense to introduce subsections in the [toc](https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022/blob/main/_toc.yml)?

I think we would then have to write the TOC as follows:

```
parts:
  - caption: Name of Part 1
    chapters:
    - file: path/to/part1/chapter1
    - file: path/to/part1/chapter2
      sections:
      - file: path/to/part1/chapter2/section1
  - caption: Name of Part 2
    chapters:
    - file: path/to/part2/chapter1
    - file: path/to/part2/chapter2
      sections:
      - file: path/to/part2/chapter2/section1
```

It may help the structure if we have, say, 3 notebooks about thresholding, to have them in a separate sub-section of their own - what do you think @zoccoler @haesleinhuepf @thawn ?

**Comment by jo-mueller** [comment]
Update: You can simply do it like this:

```
- file: day3/Readme
  sections:
  - file: day3/01_Tidy_data
  - file: day3/02_Descriptive_statistics
  - file: day3/03_Correlation
  - file: day3/04_Data_exploration
  - file: day3/05_Dimentionality_reduction/Readme
    sections:
    - file: day3/01_UMAP
    - file: day3/02_UMAP
    - file: day3/03_PCA
```
